import type { Metadata } from 'next';
import { poppins } from './ui/fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Liaoliao: A Realtime Chat Application',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${poppins.className} antialiased min-w-[100vw] overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
