// PERSONAL EVENTS
export const JOIN_ROOM = 'JOIN_ROOM';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const POPULATE_CHAT = 'POPULATE_CHAT';
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';
export const MESSAGE_FAILED = 'MESSAGE_FAILED';
export const MAKE_OFFLINE = 'MAKE_OFFLINE';

// GROUP EVENTS
export const JOIN_GROUP_ROOM = 'JOIN_GROUP_ROOM';
export const SEND_GROUP_MESSAGE = 'SEND_GROUP_MESSAGE';
export const RECEIVE_GROUP_MESSAGE = 'RECEIVE_GROUP_MESSAGE';
export const POPULATE_GROUP_CHAT = 'POPULATE_GROUP_CHAT';
export const GROUP_MESSAGE_SUCCESS = 'GROUP_MESSAGE_SUCCESS';
export const GROUP_MESSAGE_FAILED = 'GROUP_MESSAGE_FAILED';

// POLL EVENTS
export const CREATE_POLL = 'CREATE_POLL';
export const CREATE_POLL_SUCCESS = 'CREATE_POLL_SUCCESS';
export const CREATE_POLL_FAILED = 'CREATE_POLL_FAILED;';
export const SEND_VOTE = 'SEND_VOTE';
export const VOTE_SUCCESS = 'VOTE_SUCCESS';
export const VOTE_FAILED = 'VOTE_FAILED';

// LIST EVENTS
export const JOIN_LIST = 'JOIN_LIST';
